### ISSUE TITLE
Option to display Fahrenheit instead of Celsius

### ISSUE THREAD

**Issue by nomodz4real** [Zren/plasma-applet-simpleweather#15]
When using wetter or BBC the temperature is displayed in Celsius. Is there any way to add an option to display Fahrenheit as well?

**Comment by Zren** [comment]
Anything the default weather widget supports, Simple Weather can. It's just a matter of implementing it.

**[Weather Forecast](https://zren.github.io/kde/repos/#weather-forecast):** [GitHub](https://github.com/KDE/kdeplasma-addons/tree/master/applets/weather) | [All Bugs](https://bugs.kde.org/buglist.cgi?order=bug_id%20DESC&query_format=advanced&product=kdeplasma-addons&component=weather) | [New Bug](https://bugs.kde.org/enter_bug.cgi?product=kdeplasma-addons&component=weather) | [Phabricator](https://phabricator.kde.org/source/kdeplasma-addons/) | [Pull Requests](https://phabricator.kde.org/differential/query/iwcJtI0heMfD/#R) | [New PR (Repo: Plasma Addons)](https://phabricator.kde.org/differential/diff/create/)

Weather Forecast uses a C++ `Util.temperatureToDisplayString(displayTemperatureUnit, tempHigh,                                                                  reportTemperatureUnit, true)` function. So I would need to recreate it in JavaScript most likely.

* https://github.com/KDE/kdeplasma-addons/blob/master/applets/weather/plugin/util.h#L41
* https://github.com/KDE/kdeplasma-addons/blob/master/applets/weather/plugin/util.cpp#L52
* https://github.com/KDE/kdeplasma-addons/blob/master/applets/weather/package/contents/ui/main.qml#L68
* https://github.com/KDE/kdeplasma-addons/blob/master/applets/weather/package/contents/ui/main.qml#L284
* https://phabricator.kde.org/D18961

I'll take a stab at it the next time I've hacking simple weather.

**Comment by thismachinechills** [comment]
Just want to show support for this feature. Thanks for your awesome work, Zren!

Might take stab at it as well, if you're open to pull requests.

**Comment by Zren** [comment]
Patches are usually welcome, but probably not for this feature.

This one is a little complicated for a newcomer to do as the original weather widget uses C++ `plasmoid.nativeInterface.temperatureUnitId` for configuration. So you can't use the example code exactly. The patch I wrote does show how to convert it to use `plasmoid.configuration.temperatureUnitId` (like every other widget) but...

In my KDE Store widgets, I also avoid the "need to click Apply" intermediate step (which is usually by storing to `configPage.cfg_temperatureUnitId` first but not for the default weather widget). Since the example weather widget uses `nativeInterface` though, it instead calls the `signal configurationChanged()` to indicate changes were made (enabling the `Apply` button), then when you click Apply/Ok, it calls `function saveConfig()`, which uses `plasmoid.nativeInterface.saveConfig({ ... })`. Since we're not using that it'd be hard to simplify.

I've written the `contents/ui/config/ConfigUnits.qml`, just gotta implement the `Units.temperatureToDisplayString()` in a sane manner, then wrap all the format temperature calls with the new function.

**Comment by Zren** [comment]
Patches are usually welcome, but probably not for this feature.

This one is a little complicated for a newcomer to do as the original weather widget uses C++ `plasmoid.nativeInterface.temperatureUnitId` for configuration. So you can't use the example code exactly. The patch I wrote does show how to convert it to use `plasmoid.configuration.temperatureUnitId` (like every other widget) but...

In my KDE Store widgets, I also avoid the "need to click Apply" intermediate step (which is usually by storing to `configPage.cfg_temperatureUnitId` first but not for the default weather widget). Since the example weather widget uses `nativeInterface` though, it instead calls the `signal configurationChanged()` to indicate changes were made (enabling the `Apply` button), then when you click Apply/Ok, it calls `function saveConfig()`, which uses `plasmoid.nativeInterface.saveConfig({ ... })`. Since we're not using that it'd be hard to simplify.

I've written the `contents/ui/config/ConfigUnits.qml`, just gotta implement the `Units.temperatureToDisplayString()` in a sane manner, then wrap all the format temperature calls with the new function.

I also gotta handle the 0 = locale default...

**Comment by Zren** [comment]
Feature now in git master. Will probably release in a new version tonight or tomorrow.
